### ISSUE TITLE
相关推荐的背景未按预期显示

### ISSUE THREAD

**Issue by YDX-2147483647** [Devil-SX/Devil-SX.github.io#2]
```html
<a href="/2023/02/11804c51a125.html" title="那个跳楼的少年" data-pjax-state="">
    <img class="cover" src="/linear-gradient(20deg,#334d50,#cbcaa5)" alt="cover">
    <div class="content is-center">
        <div class="date"><i class="far fa-calendar-alt fa-fw"></i> 2023-02-07</div>
        <div class="title">那个跳楼的少年</div>
    </div>
</a>
```

`<img src="/linear-gradient(20deg,#334d50,#cbcaa5)">`的`src`应当指向图片源。现在这么写会让浏览器向`https://devil-sx.github.io/linear-gradient(20deg,#334d50,#cbcaa5)`发起网络请求，然后 404 Not Found。

是否应改为下面这样？

```html
<div class="relatedPosts-list">
    <div>
        <a href="/2023/02/11804c51a125.html" title="那个跳楼的少年" data-pjax-state="">
            <div class="content is-center">……</div>
        </a>
    </div>
</div>
```

```css
.relatedPosts > .relatedPosts-list > div {
	background: linear-gradient(20deg,#334d50,#cbcaa5);
}
```
